In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("../data/raw/student-mat.csv", sep=';')
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [6]:
df['pass'] = (df['G3'] >= 10).astype(int)
df[['G3','pass']].head()

   G3  pass
0   6     0
1   6     0
2  10     1
3  15     1
4  10     1

In [5]:
df['engagement_ratio'] = df['studytime'] / (df['absences'] + 1)
df['progression_trend'] = df['G2'] - df['G1']

In [7]:
df_encoded = pd.get_dummies(df, drop_first=True)

In [8]:
X = df_encoded.drop(['G3', 'pass'], axis=1)
y = df_encoded['pass']

In [9]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [10]:
pd.DataFrame(X_scaled).to_csv("../data/processed/X.csv", index=False)
y.to_csv("../data/processed/y.csv", index=False)